name: isoFarm_Env
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - r::r-rcolorbrewer
  - bioconda::rmats
  - conda-forge::r-dplyr
  - conda-forge::r-ggplot2
  - molinerislab::matrix_reduce
  - salmon
  - molinerislab::bawk
  - tbb=2020.2
  - ca-certificates
  - openssl
  - molinerislab::filter_1col
  - rsem
