STRANDED: 2
# 0 -> unstranded
# 1 -> forward
# 2 -> reverse

GENCODE_SPECIES: "hsapiens"
# hsapiens | mmusculus

GENCODE_VERSION: "32"
# 37 | M25

GENOME_ASSEMBLY: "GRCh38"
# GRCh38 | GRCm38

CORES: 32

PATH_FASTQ: "../../../fastq"
PATH_METADATA: "metadata.txt"

STAR_VERSION: "2.7.1a"
STAR_MULTIMAP_SCORE_RANGE: 1
STAR_outFilterMultimapNmax: 10
STAR_FILTER_MISMATCH: "--outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04"
STAR_OUT_SAM_TYPE: "--outSAMtype BAM Unsorted"
STAR_SHARED_MEMORY: "LoadAndKeep"

PATH_BAM: "../../../STAR/fastq"

