CORES: 32
SPECIES: hsapiens 
# hsapiens | mmusculus

STRANDED: 2
# 0 -> unstranded
# 1 -> forward
# 2 -> reverse

GENCODE:
  VERSION: "32" # 37 | M25
  ASSEMBLY: GRCh38 # GRCh38 | GRCm38

ENSEMBL:
  RELEASE: release-112

SALMON:
  LIBRARY_TYPE: A

PATH_FASTQ: ../../../fastq
PATH_METADATA: metadata.txt
PATH_BAM: ../../../STAR/fastq

STAR:
  VERSION: 2.7.1a
  MULTIMAP_SCORE_RANGE: 1
  outFilterMultimapNmax: 10
  FILTER_MISMATCH: --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04
  OUT_SAM_TYPE: --outSAMtype BAM Unsorted
  SHARED_MEMORY: LoadAndKeep


GROUP_COL: "condition"
CONDITION_COL: "clone"
TIME_POINT: "time"
GROUP_ORDER: "time_order"
