# General configuration ---
CORES: 32
EXTERNAL_REPO_DIR: "/home/reference_data/software"
SPECIES: hsapiens 
# hsapiens | mmusculus
GENCODE:
  VERSION: "32" 
  # 37 | M25
  ASSEMBLY: GRCh38 
  # GRCh38 | GRCm38
ENSEMBL:
  RELEASE: release-112
PATH_FASTQ: fastq
PATH_METADATA: ../../../metadata.txt
PATH_BAM: ../../../STAR/fastq
PATH_ANNOT_DIR: /home/reference_data/bioinfotree/task/gencode/dataset/hsapiens/32

# Salmon ---
SALMON:
  INDEX_DIR: salmon_index_no_decoy
  LIBRARY_TYPE: A

# RSEM ---
STAR:
  VERSION: 2.7.1a
  MULTIMAP_SCORE_RANGE: 1
  outFilterMultimapNmax: 10
  FILTER_MISMATCH: --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04
  OUT_SAM_TYPE: --outSAMtype BAM Unsorted
  SHARED_MEMORY: LoadAndKeep

# IPAFinder ---
CONTRASTS:
  - "p300_C_24h_vs_EV_24h"
  - "p300_FL_24h_vs_EV_24h"
